export { default as Player } from './Player.vue'

export { default as PlayerGestures } from './PlayerGestures.vue'
export { default as PlayerCaptions } from './PlayerCaptions.vue'
export { default as PlayerSliderChapters } from './PlayerSliderChapters.vue'
export { default as PlayerSliderPreview } from './PlayerSliderPreview.vue'
export { default as PlayerSliderThumb } from './PlayerSliderThumb.vue'
export { default as PlayerTimeSlider } from './PlayerTimeSlider.vue'
export { default as PlayerVolumeSlider } from './PlayerVolumeSlider.vue'
export { default as PlayerCaptionButton } from './PlayerCaptionButton.vue'
export { default as PlayerFullscreenButton } from './PlayerFullscreenButton.vue'
export { default as PlayerMuteButton } from './PlayerMuteButton.vue'
export { default as PlayerPIPButton } from './PlayerPIPButton.vue'
export { default as PlayerPlayButton } from './PlayerPlayButton.vue'
export { default as PlayerTimeGroup } from './PlayerTimeGroup.vue'
export { default as PlayerChapterTitle } from './PlayerChapterTitle.vue'

export { default as PlayerCaptionSubmenu } from './PlayerCaptionSubmenu.vue'
export { default as PlayerMenu } from './PlayerMenu.vue'
export { default as PlayerMenuRadio } from './PlayerMenuRadio.vue'
export { default as PlayerSubmenu } from './PlayerSubmenu.vue'
export { default as PlayerSubmenuButton } from './PlayerSubmenuButton.vue'

export { default as PlayerSpeedSubmenu } from './PlayerSpeedSubmenu.vue'
export { default as PlayerMenuRadioGroup } from './PlayerMenuRadioGroup.vue'
export { default as PlayerMenuRadioItem } from './PlayerMenuRadioItem.vue'
